using UnityEngine;
using Voxel.Pure;

namespace Voxel
{
    [CreateAssetMenu(fileName = "MountainStageConfig", menuName = "Voxel/Mountain Stage Config")]
    public class MountainStageConfig : ScriptableObject
    {
        [SerializeField] [Min(1)] [Tooltip("Minimum peak height in blocks above terrain surface. Peaks only form where noise exceeds PeakThreshold.")]
        private int minMountainHeight = 3;

        [SerializeField] [Min(1)] [Tooltip("Maximum peak height in blocks above terrain surface when noise = 1.")]
        private int maxMountainHeight = 12;

        [SerializeField] [Range(0f, 1f)] [Tooltip("Only place peaks where noise exceeds this. Higher = rarer, more isolated peaks (e.g. 0.8). Lower = more frequent peaks.")]
        private float peakThreshold = 0.8f;

        [SerializeField] [Min(0)] [Tooltip("Smooth noise over this radius. 0 = sharp peaks. Larger = gentler, broader slopes (can create plateaus).")]
        private int smoothRadius = 0;

        [SerializeField] private float noiseFrequency = 0.02f;
        [SerializeField] [Min(1)] private int octaves = 3;
        [SerializeField] private float lacunarity = 2f;
        [SerializeField] [Range(0f, 1f)] private float persistence = 0.5f;

        [SerializeField] [Tooltip("Material applied to blocks generated by the mountain stage. When set, Stone blocks use this instead of height-based bands.")]
        private Material material;

        public int MinMountainHeight => minMountainHeight;
        public int MaxMountainHeight => maxMountainHeight;
        public float PeakThreshold => peakThreshold;
        public int SmoothRadius => smoothRadius;
        public float NoiseFrequency => noiseFrequency;
        public int Octaves => octaves;
        public float Lacunarity => lacunarity;
        public float Persistence => persistence;
        public Material Material => material;
    }
}
